name: "Socket Basics Security Scanner"
description: "Comprehensive security scanning with SAST, secrets, container scanning, and more."
author: "Socket"

runs:
  using: "docker"
  image: "Dockerfile"

inputs:
  # Socket Configuration
  socket_org:
    description: "Socket organization slug (required for Enterprise features)"
    required: false
    default: ""
  
  socket_security_api_key:
    description: "Socket Security API key (required for Enterprise features and Dashboard configuration)"
    required: false
    default: ""

  # GitHub Integration
  github_token:
    description: "GitHub token for PR comments and API access"
    required: false
    default: ""

branding:
  icon: "shield"
  color: "blue"
